language: generic 
sudo: required 
services:
  - docker

before_install: 
  - docker build -t edsaryan/react-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true edsaryan/react-dev npm run test

after_success: 
  - docker build -t edsaryan/multi-client ./client
  - docker build -t edsaryan/multi-nginx  ./nginx
  - docker build -t edsaryan/multi-server ./server
  - docker build -t edsaryan/multi-worker ./worker


# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: docker-react
#   env: "Dockerreact-env"
#   bucket_name: elasticbeanstalk-us-east-1-166544833538
#   bucket_path: "docker-react"
#   on:
#     branch: main  
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: "$AWS_SECRET_KEY"